Tensor board
ActiveChooN/adversarial-attack-sirius pull request #3
Opened 2019-11-06 14:26 UTC by dianazagidullina

2019-11-10 15:16 UTC, ocelaiwo requested changes

2019-11-10 15:16 UTC, ocelaiwo commented on README.md
> +- Available value for dataset is SGD.
dataset -> optimizer ?

2019-11-10 15:16 UTC, ocelaiwo commented on README.md
> +- Use your favorite browser to load the tensorboard page, the address will be shown in the terminal after starting the server.
Tensorboard usage deprecated

2019-11-11 07:26 UTC, ActiveChooN approved these changes

2019-11-11 07:27 UTC, merged